FROM ubuntu:22.04 AS base

COPY README.Ubuntu.bash ./

RUN set -eux; \
    export DEBIAN_FRONTEND=noninteractive; \
    ./README.Ubuntu.bash; \
    rm README.Ubuntu.bash; \
# The en_US.UTF-8 locale is needed to run GPDB
    locale-gen en_US.UTF-8; \
# To run sshd directly, but not using `/etc/init.d/ssh start`
    mkdir /run/sshd; \
# Alter precedence in favor of IPv4 during resolving
    echo 'precedence ::ffff:0:0/96  100' >> /etc/gai.conf; \
# Packages for tests
    apt install -y rsync iproute2 fakeroot lsof sudo python3.11 python3.11-dev openjdk-17-jdk libipc-run-perl; \
    apt install -y protobuf-compiler; \
# Install allure-behave for behave tests
    pip3 install pytest gsutil behave~=1.2.6 coverage~=4.5 'mock<=5.0.0' allure-behave==2.4.0 protobuf==3.20.0; \
    pip3 cache purge

# Remove older LLVM versions and install LLVM 18
RUN sudo apt-get remove --purge -y llvm-14 llvm-14-dev clang-14 && \
    sudo apt-get update && \
    sudo apt-get install -y wget gnupg lsb-release && \
    wget https://apt.llvm.org/llvm-snapshot.gpg.key && \
    sudo apt-key add llvm-snapshot.gpg.key && \
    echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main" | sudo tee /etc/apt/sources.list.d/llvm18.list && \
    sudo apt-get update && \
    sudo apt-get install -y llvm-18 clang-18 lldb-18 && \
    sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/lib/llvm-18/bin/llvm-config 50 && \
    sudo update-alternatives --install /usr/bin/llvm-symbolizer llvm-symbolizer /usr/lib/llvm-18/bin/llvm-symbolizer 50 && \
    sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-18 50 && \
    sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 50 && \
    sudo update-alternatives --install /usr/bin/llvm-ar llvm-ar /usr/lib/llvm-18/bin/llvm-ar 50 && \
    sudo update-alternatives --install /usr/bin/llvm-ranlib llvm-ranlib /usr/lib/llvm-18/bin/llvm-ranlib 50

WORKDIR /home/gpadmin

FROM base AS build

COPY . gpdb_src

RUN mkdir /home/gpadmin/bin_gpdb

ENV TARGET_OS_VERSION=22
ENV TARGET_OS=ubuntu
ENV OUTPUT_ARTIFACT_DIR=bin_gpdb
ENV SKIP_UNITTESTS=
# To set default locale for unittests
ENV LANG=en_US.UTF-8
ENV CONFIGURE_FLAGS="--enable-debug-extensions --with-gssapi --enable-cassert --enable-debug --enable-depend"

# Compile with running mocking tests
RUN bash /home/gpadmin/gpdb_src/concourse/scripts/compile_gpdb.bash

FROM base AS code
COPY . gpdb_src
RUN rm -rf gpdb_src/.git/

FROM base AS test
COPY --from=code /home/gpadmin/gpdb_src gpdb_src
COPY --from=build /home/gpadmin/bin_gpdb /home/gpadmin/bin_gpdb
