FROM ubuntu:22.04 AS base

COPY ./README.Ubuntu.bash ./
RUN set -eux && \
    DEBIAN_FRONTEND=noninteractive ./README.Ubuntu.bash
RUN apt install -y libipc-run-perl # for --enable-tap-tests

COPY ./ /home/gpadmin/gpdb_src
WORKDIR /home/gpadmin/gpdb_src

ENV CFLAGS="-O0 -Wno-deprecated-declarations"

RUN CC="clang" CXX="clang++" CXXFLAGS="$CFLAGS" \
    ./configure --enable-gpcloud --enable-orafce --enable-tap-tests \
                --with-gssapi --with-libxml --with-openssl --with-perl \
                --with-python --with-uuid=e2fs --with-llvm --with-zstd \
                --enable-debug-extensions --enable-debug

RUN make -s -j`nproc`
